### ISSUE TITLE
Latency results for mobile devices

### ISSUE THREAD

**Issue by WYHZQ** [zhangzjn/EMO#1]
Dear Author.
Very lucky to read your work. Could you please report in your paper some latency results for some other mobile devices besides CPU and GPU?

**Comment by zhangzjn** [comment]
Hi, In this work, we only report throughputs on commonly used CPU and GPU for small models, because device-specific throughput data is not reliable for hand-designed models. In fact, latency is related to both hardware and software low-level optimization. Therefore, this experiment is more suitable for NAS processes under specific devices/software versions, which is of greater practical value. We will consider carrying out the above related experiments in the latest extended version. Thanks for your attention~

**Comment by zhangzjn** [comment]
Please view our revised version, and latency results on iPhone-14 are reported.

**Comment by WYHZQ** [comment]
> Please view our revised version, and latency results on iPhone-14 are reported.

Thank you for your reply! However, I still have some doubts about the results of iPhone 14 and have raised a new issue.
