### ISSUE TITLE
Did you compare with TensorRT?

### ISSUE THREAD

**Issue by twmht** [zhangzjn/EMO#7]
I have compared EMO-1M with RepVGG-A0, the throughput for EMO-1M is 300 fps, but RepVGG-A0 can achieve 2000 fps, the backend is TensorRT-8.5.

But as the paper stated, it's fast for embeded device, but i did not see the evidence.

Any idea?

**Comment by zhangzjn** [comment]
@twmht 

The model speed is strongly related to the hardware/accelerator library. For mobile device, we supply comparison results with SOTA Transformer based EdgeNeXt model on iPhone 14 and do not test the model on other mobile devices. But I believe EMO can be easily extended to user application scenarios because the model does not require any complex operators. 

As for EMO-1M (1.3M #Params, 0.26G FLOPs, 71.5 Top-1) versus RepVGG-A0 (8.3M #Params, 1.4G FLOPs, 72.4 Top-1), you can try balancing #Params/FLOPs/Accuracy after the specific device has been accelerated. Fortunately, a lot of hardware now has specific acceleration in the Transformer structure, and I think the speed will be impressive. 

We have considered systematically conducting experiments on various devices and updating the corresponding results in the paper. However, due to some work reasons, I have to postpone this plan at present.

**Comment by twmht** [comment]
@zhangzjn 

What is the inference engine you used for iphone14?

**Comment by zhangzjn** [comment]
@twmht We follow official classification [project](https://developer.apple.com/documentation/vision/classifying_images_with_vision_and_core_ml).

**Comment by twmht** [comment]
I see.  Thank you @zhangzjn .
